export type Service = { title: string; teaser: string; intro: string; includes: string[]; timing: string; needs: string };

export const services: Record<"ru" | "en", Service[]> = {
  ru: [
    { title: "Лицензия мастера", teaser: "Зачитываем образование и опыт, полученные вне США. Собираем, переводим и подаём документы в борд штата.", intro: "Для мастеров маникюра, лашмейкеров, бровистов, визажистов, эстетистов, мастеров депиляции, парикмахеров и барберов.", includes: ["Проверка требований штата и персональный список документов", "Перевод дипломов, сертификатов и подтверждения стажа", "Подготовка, подача и переписка с бордом"], timing: "От 7 дней до 4 месяцев — зависит от штата и готовности документов.", needs: "Дипломы, сертификаты, подтверждение опыта, SSN или ITIN, удостоверение личности." },
    { title: "Establishment license", teaser: "Лицензия на помещение: booth, кабинет или салон. Санитарные требования, инспекция и документы для борда.", intro: "Личная лицензия мастера не заменяет лицензию на помещение, где он работает.", includes: ["Проверка требований борда и санитарных норм", "Подготовка и подача заявки", "Подготовка к инспекции и перечень документов для помещения"], timing: "Зависит от штата, помещения и графика инспекции; уточним после проверки.", needs: "Адрес и тип помещения, договор аренды, личная лицензия и данные компании (если есть)." },
    { title: "Продление лицензии", teaser: "Renewal в срок и восстановление просроченной лицензии, включая continuing education, если штат его требует.", intro: "Проверяем срок действия и путь продления или восстановления по правилам вашего штата.", includes: ["Проверка срока и требований штата", "Подготовка renewal или восстановления", "Подсказки по необходимым часам continuing education"], timing: "Зависит от статуса лицензии и срока обработки бордом.", needs: "Номер лицензии и штат." },
    { title: "Перенос лицензии в другой штат", teaser: "Endorsement и reciprocity: проверяем, признаёт ли новый штат вашу лицензию, и готовим подачу.", intro: "Лицензия не переносится автоматически при переезде. У нового штата могут быть дополнительные требования.", includes: ["Проверка условий признания лицензии", "Запрос подтверждения из прежнего штата", "Подготовка и подача пакета на endorsement"], timing: "Зависит от требований нового штата и обработки подтверждения.", needs: "Действующая лицензия и штат переезда." },
    { title: "Открытие LLC", teaser: "Регистрация компании, EIN и документы для банковского счёта. Помогаем выбрать форму под ваш штат и планы.", intro: "Помогаем оформить компанию для работы с помещением, командой и отдельными бизнес-финансами.", includes: ["Подбор формы и штата регистрации", "Регистрация LLC и получение EIN", "Подготовка документов для банка и дальнейших шагов"], timing: "Зависит от штата регистрации и обработки заявки.", needs: "Желаемое название, адрес и данные участников." },
    { title: "Страхование", teaser: "Подбор и оформление professional liability, general liability и страховки помещения.", intro: "Разбираем риски именно вашей работы и объясняем различия между полисами.", includes: ["Определение нужных видов покрытия", "Сравнение вариантов понятным языком", "Помощь с оформлением полиса"], timing: "Зависит от выбранного покрытия и страховщика.", needs: "Специальность, тип помещения и сведения о наёмных мастерах." },
  ],
  en: [
    { title: "Professional license", teaser: "Use education and experience gained abroad. We assemble, translate, and submit your documents to the state board.", intro: "For nail technicians, lash and brow artists, makeup artists, estheticians, waxing specialists, hairstylists, and barbers.", includes: ["Review state requirements and create your document checklist", "Translate diplomas, certificates, and proof of experience", "Prepare the application, submit it, and correspond with the board"], timing: "7 days to 4 months, depending on your state and document readiness.", needs: "Diplomas, certificates, proof of experience, SSN or ITIN, and identification." },
    { title: "Establishment license", teaser: "Licensing for a booth, studio, or salon. Sanitation requirements, inspections, and board paperwork.", intro: "A personal professional license does not replace a license for the place where you work.", includes: ["Review board and sanitation requirements", "Prepare and submit the application", "Help you prepare for inspection and required on-site documents"], timing: "Varies by state, premises, and inspection availability.", needs: "Address and premises type, lease, personal license, and company information if applicable." },
    { title: "License renewal", teaser: "Renew on time or reinstate an expired license, including continuing education if your state requires it.", intro: "We check the license status and the appropriate renewal or reinstatement path.", includes: ["Review deadlines and state requirements", "Prepare renewal or reinstatement", "Explain required continuing education hours"], timing: "Varies by license status and board processing time.", needs: "License number and state." },
    { title: "Interstate license transfer", teaser: "Endorsement and reciprocity: we check whether your new state recognizes your license and prepare the application.", intro: "A license does not transfer automatically when you move; the new state may set additional conditions.", includes: ["Check eligibility and recognition requirements", "Request verification from the original state", "Prepare and submit the endorsement packet"], timing: "Varies by destination state and verification processing.", needs: "Current license and destination state." },
    { title: "LLC formation", teaser: "Company registration, EIN, and bank-account documents, tailored to your state and plans.", intro: "Set up a business structure for a space, team, and separate business finances.", includes: ["Review the registration structure and state", "Register the LLC and obtain an EIN", "Prepare bank documents and outline next steps"], timing: "Varies by registration state and processing time.", needs: "Preferred business name, address, and member details." },
    { title: "Insurance", teaser: "Professional liability, general liability, and premises insurance selection and setup.", intro: "We review the risks in your work and explain coverage options clearly.", includes: ["Identify the coverage you need", "Compare policy options", "Help arrange a policy"], timing: "Varies by coverage and insurer.", needs: "Your specialty, premises type, and whether you employ other professionals." },
  ],
};
